/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package revisedmenu.pending;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import revisedmenu.OracleSqlConnect;


/**
 *
 * @author mis
 */
public class Pending_Identity extends javax.swing.JInternalFrame {
String s_ba, s_trans, s_trans1, s_plus_date, s_origin, s_sur, s_fname, s_m, s_piba, s_recieved, s_pending, s_main,
       s_ids, s_doi, s_doaf, s_additional, s_denied, s_crossline, s_others;
Date Date_Plus;
    /**
     * Creates new form Pending_Identity
     */
    public Pending_Identity() {
        initComponents();
    JTextField[] textFields = {
        txtBA, txtOrigin, txtDrecieved, txtPlusDate, txtPending, txtName, txtRem
        };
    
        for (JTextField textField : textFields) {
          if (textField != txtBA) {
           textField.setText("");
            textField.setEditable(false);
             }else {
                textField.setText(""); // Optional, to clear the text in txtBA
                  textField.setEditable(true);
                     }
         }
    JCheckBox[] checkboxes = {
        cMain, cIDS, cDOI, cDOAF, cAdditional, cDenied, cCrossline,
        cOthers

              };
            for (JCheckBox checkbox : checkboxes) {
                 checkbox.setSelected(false);
                 checkbox.setEnabled(false);
            }
           cTranscode.setSelectedItem(null); 
           cTranscode.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cTranscode = new javax.swing.JComboBox<>();
        txtPlusDate = new javax.swing.JTextField();
        txtOrigin = new javax.swing.JTextField();
        txtBA = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtDrecieved = new javax.swing.JTextField();
        txtPending = new javax.swing.JTextField();
        txtRem = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cMain = new javax.swing.JCheckBox();
        cIDS = new javax.swing.JCheckBox();
        cDOI = new javax.swing.JCheckBox();
        cDOAF = new javax.swing.JCheckBox();
        cCrossline = new javax.swing.JCheckBox();
        cOthers = new javax.swing.JCheckBox();
        cAdditional = new javax.swing.JCheckBox();
        cDenied = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setTitle("Pending Identity");

        cTranscode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AOG", "A" }));
        cTranscode.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBAActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cMain.setText("Main Head Status");

        cIDS.setText("Identification Card (ID's)");

        cDOI.setText("Discrepancy on Information (Signature, Name, Birthday)");

        cDOAF.setText("Discrepancy on Application Form");

        cCrossline.setText("Crossline");

        cOthers.setText("Others");

        cAdditional.setText("Additional Requirements");

        cDenied.setText("Denied AOG/AOI/AOD");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("SELECTION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cMain)
                    .addComponent(cIDS)
                    .addComponent(cDOI)
                    .addComponent(cDOAF))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cAdditional)
                    .addComponent(cDenied)
                    .addComponent(cCrossline)
                    .addComponent(cOthers))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cAdditional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cDenied)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cCrossline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cOthers))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cMain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cIDS)
                        .addGap(0, 0, 0)
                        .addComponent(cDOI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cDOAF)))
                .addGap(10, 10, 10))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Transaction Code");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Plus Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Origin");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("BA No");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Date Received");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Ref/Pending No.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Remarks");

        Save.setText("Save");
        Save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Cancel.setText("Cancel");
        Cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Clear.setText("Delete from File");
        Clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton4.setText("Close");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRem, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cTranscode, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBA, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPlusDate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(txtOrigin)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDrecieved, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(txtPending, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTranscode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlusDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDrecieved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(txtRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Cancel)
                    .addComponent(Clear)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBAActionPerformed
        Connection conn_obj = OracleSqlConnect.ConnectDB();
        SimpleDateFormat date_plus = new SimpleDateFormat("dd-MMM-yyyy");  
        s_ba = String.format("%8s",txtBA.getText());
        s_ba = s_ba.replace(' ','0');
        txtBA.setText(s_ba);
        s_ba = txtBA.getText().trim();
        

            try {
                 String search_sql = "SELECT * FROM MEMBER1 WHERE IDNO = '"+s_ba+"'";
                 PreparedStatement stmt_search = conn_obj.prepareStatement(search_sql); 
                 ResultSet rs_search;
                 rs_search = stmt_search.executeQuery();
         
                 int a = 0;
                 while(rs_search.next()){
                     a++;
                     
                     s_ba = rs_search.getString("IDNO");
                     s_sur = rs_search.getString("SNAME");
                     s_fname = rs_search.getString("FNAME");
                     s_m = rs_search.getString("MNAME");
                     Date_Plus = rs_search.getDate("PLUSDATE");
                       if(Date_Plus == null)
                       {
                           s_plus_date = "";
                       }
                       else{
                           s_plus_date = date_plus.format(Date_Plus);        
                           }
                     s_origin = rs_search.getString("ORGN");
                     s_piba = rs_search.getString("ISPIBA");
                 }
                 
                 
                 
           if (s_ba.length() == 0 || s_ba.equals("00000000")){                     
                    JTextField[] textFields = {
                    txtOrigin, txtDrecieved, txtPlusDate, txtPending, txtName, txtRem};

                    for (JTextField textField : textFields) {                            
                    textField.setEditable(false);
                    txtBA.setText("");
                    }

                    JCheckBox[] checkboxes = {
                    cMain, cIDS, cDOI, cDOAF, cAdditional, cDenied, cCrossline,
                    cOthers};   

                    for (JCheckBox checkbox : checkboxes) {
                    checkbox.setSelected(false);
                    checkbox.setEnabled(false);
                     }
                    cTranscode.setEnabled(false); 
                    cTranscode.setSelectedItem(null); 
                                 
                   JOptionPane.showMessageDialog(null, "Input BA.","Error", JOptionPane.INFORMATION_MESSAGE);           
           }else{
                 if(a > 0){
                     txtName.setText(s_sur + "," + s_fname + s_m);
                     txtOrigin.setText(s_origin);
                     txtPlusDate.setText(s_plus_date);
                              
                   
                     if(!txtBA.getText().isEmpty()){
                     String search_sql2 = "SELECT * FROM IDENTITY_STATUS WHERE IDNO = '"+s_ba+"'";
                         
                     }
                     
                     
                     
                     
                     
                     
                     
                    JTextField[] textFields = {
                    txtBA, txtOrigin, txtDrecieved, txtPlusDate, txtPending, txtName, txtRem};

                    for (JTextField textField : textFields) {                            
                    textField.setEditable(true);
                    }

                    JCheckBox[] checkboxes = {
                    cMain, cIDS, cDOI, cDOAF, cAdditional, cDenied, cCrossline,
                    cOthers};   

                    for (JCheckBox checkbox : checkboxes) {
                    checkbox.setSelected(true);
                    checkbox.setEnabled(true);
                     }
                    cTranscode.setEnabled(true);   
   
                  
                 }else{
                      JTextField[] textFields = {
                    txtOrigin, txtDrecieved, txtPlusDate, txtPending, txtName, txtRem};

                    for (JTextField textField : textFields) {                            
                    textField.setEditable(false);
                    txtBA.setText("");
                    }

                    JCheckBox[] checkboxes = {
                    cMain, cIDS, cDOI, cDOAF, cAdditional, cDenied, cCrossline,
                    cOthers};   

                    for (JCheckBox checkbox : checkboxes) {
                    checkbox.setSelected(false);
                    checkbox.setEnabled(false);
                     }
                    cTranscode.setEnabled(false); 
                    cTranscode.setSelectedItem(null); 
                                 
                   JOptionPane.showMessageDialog(null, "INVALID BA.","Error", JOptionPane.INFORMATION_MESSAGE);    
                 }
                 
              }
                
               
            
            
            }catch (SQLException ex) {
                Logger.getLogger(Pending_Identity.class.getName()).log(Level.SEVERE, null, ex);
            
               } 
    }//GEN-LAST:event_txtBAActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
     JTextField[] textFields = {
        txtBA, txtOrigin, txtDrecieved, txtPlusDate, txtPending, txtName, txtRem
        };
    
        for (JTextField textField : textFields) {
          if (textField != txtBA) {
           textField.setText("");
            textField.setEditable(false);
             }else {
                textField.setText(""); // Optional, to clear the text in txtBA
                  textField.setEditable(true);
                     }
         }
     JCheckBox[] checkboxes = {
        cMain, cIDS, cDOI, cDOAF, cAdditional, cDenied, cCrossline,
        cOthers

              };
            for (JCheckBox checkbox : checkboxes) {
                 checkbox.setSelected(false);
                 checkbox.setEnabled(false);
            }
           cTranscode.setSelectedItem(null); 
           cTranscode.setEnabled(false);
    }//GEN-LAST:event_CancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Save;
    private javax.swing.JCheckBox cAdditional;
    private javax.swing.JCheckBox cCrossline;
    private javax.swing.JCheckBox cDOAF;
    private javax.swing.JCheckBox cDOI;
    private javax.swing.JCheckBox cDenied;
    private javax.swing.JCheckBox cIDS;
    private javax.swing.JCheckBox cMain;
    private javax.swing.JCheckBox cOthers;
    private javax.swing.JComboBox<String> cTranscode;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtBA;
    private javax.swing.JTextField txtDrecieved;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrigin;
    private javax.swing.JTextField txtPending;
    private javax.swing.JTextField txtPlusDate;
    private javax.swing.JTextField txtRem;
    // End of variables declaration//GEN-END:variables
}
